using System;
using System.Collections.Generic;
using System.Linq;
using ISO8583Net.Packager;
using Microsoft.Extensions.DependencyInjection;

namespace ISO8583Net.Server.Pipeline.Handlers;

/// <summary>
/// Builds an MTI → handler(s) lookup map at startup from all
/// <see cref="IMessageHandler"/> instances registered in DI.
/// </summary>
public sealed class HandlerRegistry
{
    private readonly Dictionary<string, List<IMessageHandler>> _handlers = new();
    private readonly List<IMessageHandler> _catchAll = new();
    private readonly List<IMessageHandler> _allHandlers = new();
    private ISOMessageTypesPackager? _msgTypes;

    /// <summary>
    /// Build the registry from all registered handlers.
    /// </summary>
    public HandlerRegistry(IEnumerable<IMessageHandler> handlers)
    {
        foreach (var handler in handlers)
        {
            _allHandlers.Add(handler);

            foreach (var mti in handler.SupportedMTIs)
            {
                if (mti == "*")
                {
                    _catchAll.Add(handler);
                }
                else
                {
                    if (!_handlers.TryGetValue(mti, out var list))
                    {
                        list = new List<IMessageHandler>();
                        _handlers[mti] = list;
                    }
                    list.Add(handler);
                }
            }
        }
    }

    /// <summary>
    /// Validates every registered handler MTI against the dialect. Must be called once the
    /// dialect/packager has been loaded (see <c>PipelineHost.ValidateHandlers</c>). A handler
    /// that declares an MTI the dialect does not define — including any terminal "9xxx" MTI, or
    /// a wildcard other than exactly "*" — fails fast with an <see cref="InvalidOperationException"/>
    /// before any connection is accepted.
    /// </summary>
    public void ValidateAgainstDialect(ISOMessageFieldsPackager fieldsPackager)
    {
        var msgTypes = fieldsPackager.GetMessageTypesPackager();
        _msgTypes = msgTypes;

        if (msgTypes == null)
            return;

        var errors = new List<string>();

        foreach (var handler in _allHandlers)
        {
            foreach (var mti in handler.SupportedMTIs)
            {
                if (mti == "*")
                    continue;

                if (mti.Contains('*'))
                {
                    errors.Add($"Handler {handler.GetType().Name} declares wildcard MTI '{mti}'; only \"*\" is allowed as a catch-all.");
                }
                else if (mti.Length == 4 && mti[0] == '9')
                {
                    errors.Add($"Handler {handler.GetType().Name} declares terminal format-error MTI '{mti}' (9xxx); format-error responses are generated by the dispatcher, not by business handlers.");
                }
                else if (!msgTypes.Contains(mti))
                {
                    errors.Add($"Handler {handler.GetType().Name} declares MTI '{mti}' which is not defined in the dialect.");
                }
            }
        }

        if (errors.Count > 0)
        {
            throw new InvalidOperationException(
                "Handler registration failed validation against the dialect:\n  - " +
                string.Join("\n  - ", errors));
        }
    }

    /// <summary>
    /// Get all handlers for a given MTI, plus any applicable catch-all handlers.
    /// When the dialect is known (see <see cref="ValidateAgainstDialect"/>), the catch-all is
    /// only consulted for MTIs the dialect defines (or the empty/absent-MTI case); an undefined
    /// MTI yields no handlers so the dispatcher can emit its format-error response.
    /// </summary>
    public IReadOnlyList<IMessageHandler> GetHandlers(string mti)
    {
        var result = new List<IMessageHandler>();

        if (_handlers.TryGetValue(mti, out var specific))
            result.AddRange(specific);

        if (ShouldIncludeCatchAll(mti))
            result.AddRange(_catchAll);

        return result;
    }

    private bool ShouldIncludeCatchAll(string mti)
    {
        // No dialect loaded yet (tests/legacy): stay permissive.
        if (_msgTypes == null)
            return true;

        // Header-only / corrupt messages have no MTI: the catch-all still sees them so they can
        // be observed (the dispatcher's own guards handle D8 headers before this point).
        if (string.IsNullOrEmpty(mti))
            return true;

        // Only dialect-defined MTIs reach the catch-all; undefined MTIs must not.
        return _msgTypes.Contains(mti);
    }

    /// <summary>
    /// Total number of registered handlers (including catch-all).
    /// </summary>
    public int HandlerCount => _handlers.Values.Sum(l => l.Count) + _catchAll.Count;

    /// <summary>
    /// The distinct MTIs (excluding "*") for which at least one handler is registered, sorted.
    /// </summary>
    public IReadOnlyList<string> RegisteredMTIs => _handlers.Keys.OrderBy(m => m).ToList();

    /// <summary>
    /// Whether at least one catch-all ("*") handler is registered.
    /// </summary>
    public bool HasCatchAll => _catchAll.Count > 0;
}
